### ISSUE TITLE
sonar dotnet fails on importing test coverage results

### ISSUE THREAD

**Issue by baywet** [SonarSource/sonar-csharp#469] opened 2017-06-23 14:26 UTC
### Description

We currently use VSTS builds in our pipeline. We're using the latest tasks provided by SonarQube (2.1.2, scanner 2.3.2) and when SonarQube tries to import code coverage results it fails with the following stack trace.

### Repro steps
Build definition
- Sources
- Nuget restore
- prepare SQ analysis
- Build solution
- vstest
- complete SQ analysis
- Symbols
- copy to artifacts
- publish artifacts
Error logs 
```
ERROR: Error during SonarQube Scanner execution
2017-06-23T12:49:45.8884077Z ##[error]java.lang.IllegalStateException: Error while parsing the XML file: C:\agentv2\_work\6\s\TestResults\BuildAdmin_AGENT-BUILD 2017-06-23 08_49_03\In\AGENT-BUILD\BuildAdmin_AGENT-BUILD 2017-06-23 08_48_48.coverage
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.XmlParserHelper.nextStartTag(XmlParserHelper.java:67)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.XmlParserHelper.checkRootTag(XmlParserHelper.java:49)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.VisualStudioCoverageXmlReportParser$Parser.checkRootTag(VisualStudioCoverageXmlReportParser.java:117)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.VisualStudioCoverageXmlReportParser$Parser.parse(VisualStudioCoverageXmlReportParser.java:54)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.VisualStudioCoverageXmlReportParser.accept(VisualStudioCoverageXmlReportParser.java:37)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.VisualStudioCoverageXmlReportParser.accept(VisualStudioCoverageXmlReportParser.java:30)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.CoverageCache.readCoverageFromCacheOrParse(CoverageCache.java:39)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.CoverageAggregator.aggregate(CoverageAggregator.java:109)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.CoverageAggregator.aggregate(CoverageAggregator.java:100)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.CoverageReportImportSensor.analyze(CoverageReportImportSensor.java:77)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.CoverageReportImportSensor.execute(CoverageReportImportSensor.java:72)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:240)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
2017-06-23T12:49:45.8884077Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-06-23T12:49:45.8884077Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2017-06-23T12:49:45.8884077Z ##[error]at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2017-06-23T12:49:45.8884077Z ##[error]at java.lang.reflect.Method.invoke(Unknown Source)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
2017-06-23T12:49:45.8884077Z ##[error]at com.sun.proxy.$Proxy0.execute(Unknown Source)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonarsource.scanner.cli.Main.main(Main.java:61)
2017-06-23T12:49:45.8884077Z ##[error]Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character 'P' (code 80) in prolog; expected '<'
2017-06-23T12:49:45.8884077Z ##[error]at [row,col {unknown-source}]: [1,1]
2017-06-23T12:49:45.8884077Z ##[error]at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:647)
2017-06-23T12:49:45.8884077Z ##[error]at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2054)
2017-06-23T12:49:45.8884077Z ##[error]at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1131)
2017-06-23T12:49:45.8884077Z ##[error]at org.sonar.plugins.dotnet.tests.XmlParserHelper.nextStartTag(XmlParserHelper.java:60)
2017-06-23T12:49:45.8884077Z ##[error]... 41 more
2017-06-23T12:49:45.8884077Z ##[error]ERROR:
2017-06-23T12:49:45.8884077Z ##[error]ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
2017-06-23T12:49:45.8884077Z 08:49:45.841  Creating a summary markdown file...
2017-06-23T12:49:45.8884077Z ##[error]The SonarQube Scanner did not complete successfully
2017-06-23T12:49:45.8884077Z ##[error]08:49:45.841  Post-processing failed. Exit code: 1
2017-06-23T12:49:45.9040330Z ##[error]System.Exception: Unexpected exit code received from batch file: 1
```

See attached coverage file
[1099...105.coverage.zip](https://github.com/SonarSource/sonar-csharp/files/1098055/1099.105.coverage.zip)
See provided configuration parameters for the task.
```
/d:sonar.cs.vscoveragexml.reportsPaths=$(System.DefaultWorkingDirectory)\**\*.coverage
```
I'm also getting this warning at the beginning so maybe something is wrong with VS2017?
```
WARNING: Failed to find the code coverage command line tool. Possible cause: Visual Studio is not installed, or the installed version

 does not support code coverage
```
### Expected behavior

Code coverage analysis to work

### Actual behavior

Code coverage (and static analysis) fails with provided details

### Known workarounds

none

### Related information

* SonarC# Version
* Visual Studio Version 2017 enterprise
* If running through the Scanner for MSBuild, its version 2.3.2

**Comment by Evangelink** [comment] 2017-06-23 15:04
Hi @baywet!

It seems like you are providing a `.coverage` file while the extension expects a `.coveragexml` file. (see the [documentation](https://docs.sonarqube.org/x/CoBh)).

Also the latest version of the task is 3.0.0 but my previous sentence is also valid for the version you have.

I am closing this ticket, let me know if it didn't worked.

Cheers,
Amaury

**Closed by Evangelink** 2017-06-23 15:04 UTC
Labels: Type: Question

**Comment by baywet** [comment] 2017-06-27 13:21
Thanks very much! For some reason I had not come across the piece of documentation before. Sorry for disturbing.
Also upgraded to latest version of the task, works like a charm.

**Comment by Evangelink** [comment] 2017-06-27 13:27
Glad to know the issue is solved!
