### ISSUE TITLE
Fix S2583: false positive with null coalesce operator

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-csharp#1870] opened 2018-09-21 12:44 UTC
### Repro

``` 
public void func(string s)
        {
            // "S2583 Change this condition so that it does not always evaluate to 'false'; some subsequent code is never executed."
            if (s?.Equals("blah", System.StringComparison.OrdinalIgnoreCase) ?? false)
            {
                // do something
            }
        }
```

### Expected behavior
S2583 is not raised

### Related information

* SonarC# Version: 7.5.0.6605

Note: original bug report is [here](https://community.sonarsource.com/t/s2583-false-positive/2742).

**Comment by Evangelink** [comment] 2018-10-08 08:55
Duplicate of #1347

**Closed by Evangelink** 2018-10-08 08:55 UTC
Labels: Area: Rules, Area: Symbolic Execution, Community, Type: False Positive
