### ISSUE TITLE
Error while parsing protobuf file

### ISSUE THREAD

**Issue by nikitha789** [SonarSource/sonar-csharp#1868] opened 2018-09-20 13:10 UTC
I am running sonarscanner for MSbuild using the latest 7.3 sonnarqube server and using Sonarscanner for MSbuild on the CI. 

I have 3 steps defined 
Begin
msbuild
end

 SonarC# Version : 7.5 (build 6605)
Scanner for MSBuild, its version : sonar-scanner-msbuild-4.3.1.1372
SonarServer : 7.3

Error Encountered: 
`ERROR: unexpected error while parsing protobuf file: C:\TG_Test\.sonarqube\out\239\output-cs\token-cpd.pb
ERROR: Caused by: Protocol message was too large.  May be malicious.  Use CodedInputStream.setSizeLimit() to increase the size limit.
ERROR: 
Process returned exit code 1
The SonarQube Scanner did not complete successfully
Creating a summary markdown file...
 Post-processing failed. Exit code: 1
Process exited with code 1
Process exited with code 1`

**Comment by Evangelink** [comment] 2018-09-24 08:18
Hi @nikitha789,

Could you provide a small project where the error happens all the time? I made a quick test with a small console application and cannot reproduce the issue.

Cheers,
Amaury

**Comment by nikitha789** [comment] 2018-09-24 17:46
Hello @Evangelink,

thank you for your reposnse, Is there any other way this can be analysed. I can send you the  token-cpd.pb from .sonarqube folder, if that can be used to analyse the error!

**Comment by Evangelink** [comment] 2018-09-25 09:33
Hi @nikitha789,

Please do send us the `token-cpd.pb` file, we will try to see if we have enough info with it to find out what's wrong.

**Comment by nikitha789** [comment] 2018-09-25 13:38
Hi @Evangelink ,

Attached is the file as requested. Any lead on the error would be greatly appreciated
[token-cpd.zip](https://github.com/SonarSource/sonar-csharp/files/2415450/token-cpd.zip)
.

**Comment by Evangelink** [comment] 2018-09-25 15:59
Hi @nikitha789,

Thank you for the feedback.
I have created ticket #1891 which should fix your issue. The fix will be available on the next version.

**Comment by Evangelink** [comment] 2018-10-01 12:02
Hi @nikitha789,

I am closing this ticket as it should be fixed with the next release of SonarC# (7.6). Please feel free to re-open/comment here if you are still experiencing the issue.

Cheers,
Amaury

**Closed by Evangelink** 2018-10-01 12:02 UTC
