### ISSUE TITLE
Email notifications for excluded files

### ISSUE THREAD

**Issue by KevinSchiener** [SonarSource/sonar-csharp#650] opened 2017-08-04 09:54 UTC
### Description

We use Source File Exclusions to filter out some generated code files (e.g. EntityFramework migrations) and occasionally get email notifications on the excluded files. If we then click the issue link in the email there is an error saying that:

>The file was removed, no source code can be displayed.

### Repro steps

1. Exclude some files that have errors using Project > Analysis Scope > Source File Exclusions > `**/Migrations/*.cs`

2. Make sure SCM mapping to user account and automatic assignment of issues is enabled.

3. Enable notifications on new issues assigned to your account.

4. Commit some unrelated code and wait.

### Expected behavior

I will not get any emails for excluded files.

### Actual behavior

I get two emails like this:

First:
> 1 new issues (new debt: 20min)
> 
>     Severity
>         Blocker: 0    Critical: 0    Major: 1    Minor: 0    Info: 0
> 
>     Rules
>         Methods should not have too many parameters (cs): 1
> 
>     Tags
>         brain-overload: 1
> 
>     Most impacted files
>         TestDataInitializer.cs: 1

Second:
> Rule: Methods should not have too many parameters
> Message: Method has 8 parameters, which is greater than the 7 authorized.
> 
> Resolution: FIXED
> Status: CLOSED (was OPEN)

This happens at least once a day. We run around 10 analyses per day. A colleague get around 300 emails if this error happens.

### Known workarounds

Disable notifications or mark all issues as "Won't fix".

### Related information

* SonarQube Version: 6.4.0.25310

I'm happy to report this on the core SonarQube issue tracker, but I have not yet found a place or way to do that.

**Comment by Evangelink** [comment] 2017-08-07 16:52
Hi @KevinSchiener, I have asked some colleagues to answer you but generally people post a question on StackOverflow or on our Google Group (see https://www.sonarqube.org/community/).

**Comment by KevinSchiener** [comment] 2017-08-08 06:57
Thank you. I only saw the "How to contribute" section the last time I checked the community page. My bad. If you want you can close this issue and I just repost in the google group. Using StackOverflow for bug reports would feel wrong to me. :)

**Comment by fmallet** [comment] 2017-08-08 14:22
Thanks @KevinSchiener for this bug report. I haven't yet managed to reproduce the issue on my side (which doesn't mean that there isn't any issue). Could you just confirm that you don't play directly with the `sonar.exclusions` parameter when doing some analysis and that this parameter is only set on server side ? I'm asking this question because this is as-is some analysis would take into account the excluded source files and some others not. Thx

**Comment by KevinSchiener** [comment] 2017-08-09 07:29
@fmallet First of all thank you for having a look at this.

I checked the analysis commandline and the XML config and we don't set any exclusions there. We exlusively use the exclusions set on the web UI. The exclusions are set on the project settings, not the global settings in case that makes any difference.

This morning the problem occurred again and I checked the corresponding analysis.

Email at 12:40: [SONARQUBE] You have 1 new issues on project XYZ
Email at 08:30: [SONARQUBE] XYZ, change on issue #AV3D-sx9wPauaV2DRBXS

The following are the analyses that were run during this time frame:
![image](https://user-images.githubusercontent.com/11420486/29109832-cadf02e0-7ce4-11e7-8f97-82b04f961a3d.png)

![image](https://user-images.githubusercontent.com/11420486/29109920-25cf12b2-7ce5-11e7-89c1-ad76a8f86192.png)

I have no idea why it keeps switching the quality profiles back and forth. We didn't (intentionally) change anything there.

**Comment by bellingard** [comment] 2017-08-24 10:30
Hi @KevinSchiener, I think you nailed down the root cause of the behaviour you experience. Now, you've got to find why the quality profile regularly changes. 

To  enforce a given quality profile, make sure that:
* In your project "Administration > Quality Profiles" page, the C# quality profile you want is actually selected
* In your CI system, nothing sets the deprecated "sonar.profile" analysis parameter to run the analysis

**Comment by KevinSchiener** [comment] 2017-08-24 12:12
Hello @bellingard,

we could further correlate the problem (which just occurred again today) to an error in our MS SQL server.

> There is insufficient system memory in resource pool 'internal' to run this query.

We upped the memory for the server, but I get the feeling that SonarQubes error handling might be a bit brittle in this scenario. We're not yet sure if the error is caused by the analysis or the webpage, but it seems that some queries bring the SQL server to its knees. (It was running on 8GB RAM, now 32GB.)

**Comment by bellingard** [comment] 2017-08-24 12:42
OK, I think we should stop the discussion here, and start a new thread on the Google group. Nothing in this is related to the C# analyzer, so I don't want to "pollute" their backlog with issues related to SonarQube itself. Are you fine with this?

**Comment by KevinSchiener** [comment] 2017-08-24 12:47
@bellingard, good idea.

**Comment by bellingard** [comment] 2017-08-24 13:18
Thanks @KevinSchiener, I'm therefore closing the ticket.

**Closed by bellingard** 2017-08-24 13:18 UTC
Labels: Type: Question

**Comment by Evangelink** [comment] 2017-08-24 13:48
@KevinSchiener @bellingard thx guys.
