### ISSUE TITLE
Code coverage from TFS 2017 not being shown/imported in SonarQube

### ISSUE THREAD

**Issue by Rutix** [SonarSource/sonar-csharp#805] opened 2017-10-05 07:38 UTC
### Description

We cannot seem to get the import of CodeCoverage working on SonarQube (5.6.3) with plugin version 6.4.1.3596. We are using an on-premise TFS 2017 update 3 with SonarQube extension with version 3.0.2. We get analysis of the code just fine but the code coverage doesn't want to appear. Looking through the log files everything seem to be in order and I am out of idea's of where to look.

I tried the workaround in #492 but that also doesn't work. The reportPath is set correctly according to the log.

I added the logs and the .coveragexml file to the issue.
[logs_2931.zip](https://github.com/SonarSource/sonar-csharp/files/1358373/logs_2931.zip)

### Repro steps

1. Create a standard VSTS build for .Net and add SonarQube tasks on a .Net project with coverage enabled.
2. Have a SonarQube 5.6.3 running with plugin 6.4.1.3596
3. The code coverage doesn't appear in the project page.

### Expected behavior

I expect the code coverage results to appear in the project page.

### Actual behavior

The code coverage widget and data on the project page stays with no data.

### Known workarounds

Please provide a description of any known workarounds.

### Related information
The code we are running is targeted for .NET standard and the test project runs at .NET 4.7. Don't know if this is relevant. 
* SonarC# Version 6.4.1.3596
* Visual Studio Version 2017 (TFS 2017 update 3)
* If running through the Scanner for MSBuild, its version 3.0.2

**Comment by Evangelink** [comment] 2017-10-13 13:27
Hi @Rutix,
Thanks for the feedback. I am closing the ticket here because it seems to be linked to some regression within the scanner for msbuild (see this ticket).

**Closed by Evangelink** 2017-10-13 13:27 UTC
