### ISSUE TITLE
S1450 - can we use static readonly fields?

### ISSUE THREAD

**Issue by sm-g** [SonarSource/sonar-csharp#1399] opened 2018-05-12 20:04 UTC
```
private static readonly char[] ForbiddenChars = ":\n\t".ToCharArray();

// this really used only in one place:
if (GetAllNameChars()?.IndexOfAny(ForbiddenChars) >= 0)
   yield return new ValidationResult($"Some of name contains forbidden char");
```

SonarLint wants to declare this field in method

### Related information

* SonarC# Version 7.1.0
* Visual Studio Version 15.7.1

**Comment by Evangelink** [comment] 2018-05-15 16:03
Hi @sm-g,

I cannot reproduce the issue with the code snippet you provided. Could you test again to be sure this is raising an issue?

**Comment by Evangelink** [comment] 2018-08-06 15:26
I am closing the issue. Let me know if you still experience any problem with SonarC# 7.4+.

**Closed by Evangelink** 2018-08-06 15:26 UTC
