### ISSUE TITLE
Fix S3881: Rule should not raise an issue when inheriting from Form/UserControl with default implementation of Dispose method

### ISSUE THREAD

**Issue by zmanbb** [SonarSource/sonar-csharp#901] opened 2017-11-02 18:22 UTC
### Description

When Windows Form/UserControl is inheriting from another Form / UserControl (both with default implementation of Dispose method, generaded by the Designer), S3881 is raised.

### Repro steps

1. Create new Windows Forms project. 

2. Add 2 forms, Form1 and Form2. Change code in Form2 so it inherits from Form1.

3. Add SonarAnalyzer.CSharp (ver. 6.5) from NuGet.

4. S3881 is raised in Form2.

### Expected behavior

The S3881 should not be raised. 
The S3881 is not raised in ver. 6.4.

### Related information

* Attached is the sample project: [WindowsFormsApp3.zip](https://github.com/SonarSource/sonar-csharp/files/1438876/WindowsFormsApp3.zip)

**Comment by Evangelink** [comment] 2017-11-03 15:47
Hi @zmanbb,
Thanks for the feedback! I can reproduce the issue with the attached code sample.

**Comment by zmanbb** [comment] 2017-11-03 20:24
Hi. I hope this will get fixed as soon as possible. Rule S3881 in version 6.5 is pretty much useless for WinForms projects as long as this bug is present.

**Comment by zmanbb** [comment] 2018-03-06 22:26
Any update on this issue?

**Comment by michalb-sonar** [comment] 2018-03-07 11:33
@zmanbb: this problem is now fixed - updating the sonar analyzer version makes the problem from your sample solution go away.
Thanks again for feedback; sorry it took us so long to respond. Feel free to re-open issue if the problem was not resolved for you.

**Closed by michalb-sonar** 2018-03-07 11:33 UTC
Labels: Status: Confirmed, Type: False Positive
