### ISSUE TITLE
Missing Google.Protobuf in SonarAnalyzer

### ISSUE THREAD

**Issue by rosieks** [SonarSource/sonar-csharp#602] opened 2017-07-26 09:57 UTC
### Description

After installing SonarAnalyzer.CSharp new warning appears:

Severity: Warning
Code: IDE1003
Description: Analyzer assembly 'c:\users\me\documents\visual studio 2017\Projects\ConsoleApp2\packages\SonarAnalyzer.CSharp.6.2.0.2536\analyzers\SonarAnalyzer.dll' depends on 'Google.Protobuf, Version=3.1.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.

### Repro steps

1. Create new Console Application
2. Install nuget package `SonarAnalyzer.CSharp`
3. Close Visual Studio
4. Open new instance of Visual Studio and open created console application

### Expected behavior

No warning

### Actual behavior

Warning IDE1003 appears

### Known workarounds

Don't know

### Related information

* SonarC# Version: 6.2.0.2536
* Visual Studio Version: 15.2

**Comment by Evangelink** [comment] 2017-08-02 08:32
Hi @rosieks,
I have tried to reproduce the issue on VS2015U3 and VS2017U2 and I can't manage to have it. I have only 2 warnings S1118 and S1186.

Could you give me more information or create a small reproducer?

**Comment by RalfKoban** [comment] 2017-08-02 10:03
Hi @Evangelink.
I have the same issue on my side.

My Visual Studio:
Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.7.02053

How to reproduce:

 1. Start Visual Studio 2017
 2. In the application menu click "File > New > Project..."
 3. Select "Console App (.NET Framework)" and click [OK]
 4. In Solution explorer, right-click the solution node and click "Manage NuGet Packages for solution..."
 5. In the "NuGet - Solution" window, browse the "SonarAnalyzer.CSharp" package on package source "nuget.org"
 6. Select the found "SonarAnalyzer.CSharp" v6.2.0.2536, then tick the checkbox for the console application project and click [Install]
 7. After installation finished, close Visual Studio
 8. Open Visual Studio
 9. Click on "File > Recent Projects and Solutions" and click the created solution
10. Go to the "Error List" view and select "Entire Solution" and "Build + IntelliSense"
11. (Ensure that the errors, warnings and messages are toggled on the "Error List" view)

-> The very first entry is now "IDE1003..."

Best regards,
Ralf

**Comment by Evangelink** [comment] 2017-08-02 10:27
Hi guys,
I did exactly what you described @RalfKoban but I cannot reproduce the error. I have created a github repository to show you my console app: https://github.com/Evangelink/missing-protobuf
Fill free to push PR onto it for changes that would make the analyzer fail.

**Comment by RalfKoban** [comment] 2017-08-02 10:59
Hi @Evangelink,

when I download and unzip the provided github repro, I cannot reproduce it as described by my steps.
What I need to do in addition is to "Restore NuGet Packages" via right-click on the solution node in the solution explorer.

If I do so, I get following warning shown in the Error List:
Severity	Code	Description	Project	File	Line	Suppression State
Warning	IDE1003	Analyzer assembly 'D:\TEMP\missing-protobuf-master\ConsoleApp1\packages\SonarAnalyzer.CSharp.6.2.0.2536\analyzers\SonarAnalyzer.dll' depends on 'Google.Protobuf, Version=3.1.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.	ConsoleApp1		1	Active


Please note that I did not trigger anything else (so no build or whatever).

Best regards,
Ralf

**Comment by Evangelink** [comment] 2017-08-02 11:52
I can manage to get IDE1001 by removing the `packages` folder after opening the solution and doing `Restore NuGet Packages` but I can't manage to get IDE1003. Do you have this error everytime? Does it prevent you from actually using the analyzer or do you have the warnings raised by our analyzer?

**Comment by rosieks** [comment] 2017-08-02 13:06
For me this error does not occure every time and actually I can see SonarLint warnings. I'm not sure how it works internally but maybe it's nice to shut down all visual studios and then open one with project that has SonarAnalyzer. I noticed that when I open another Visual Studio with the same project there is no this warning, but it can be just coincidence.

**Comment by Evangelink** [comment] 2017-08-02 13:09
We actually rely on Visual Studio and Roslyn mechanisms so we have only few control over those (not saying there is no potential bug on our side). I will do a few more investigations but if this is just a temporary message for you two I will close this ticket.

**Comment by RalfKoban** [comment] 2017-08-03 05:41
For me it currently looks like it's only a temporary message.

**Closed** 2017-08-10 10:55 UTC
Labels: Type: Bug, Type: Question

**Comment by zuckerthoben** [comment] 2018-01-25 08:25
I get the same warnings for some time now. Once per project in my solution. Sadly I don't have a better repro. Is this still a known issue?
