### ISSUE TITLE
S2259 false positive with nameof

### ISSUE THREAD

**Issue by tamasvajk** [SonarSource/sonar-csharp#977] opened 2017-11-22 20:46 UTC
```
static void Main(string[] args)
{
    if (args == null)
    {
        Console.WriteLine(nameof(args.ToString)); // S2259 false positive 
    }
}

```

**Comment by valhristov** [comment] 2017-11-23 08:17
Hi Tamas, long time, no see :) I think this is duplicate of #923, which we recently fixed.

**Closed by valhristov** 2017-11-23 08:17 UTC

**Comment by tamasvajk** [comment] 2017-11-23 08:22
Perfect. Thanks.
