### ISSUE TITLE
Unable to write VB analyzer for this plugin

### ISSUE THREAD

**Issue by vickyrocky** [SonarSource/sonar-csharp#1849] opened 2018-09-12 07:26 UTC
### Description
I am trying to write my own analyzer for VB for using in sonarqube and this plugin already contains some VB rules which has been implemented but those rules are written in c# rather than vb so i started writing using c# for the vb analyzer but now getting error as test is failing : 

Test Name:	TestMethod1
Test FullName:	Analyzer3.Test.UnitTest.TestMethod1
Test Source:	C:\Users\\source\repos\Analyzer3\Analyzer3\Analyzer3.Test\Analyzer3UnitTests.cs : line 17
Test Outcome:	Failed
Test Duration:	0:00:01.9175614

Result StackTrace:	
at TestHelper.DiagnosticVerifier.VerifyDiagnosticResults(IEnumerable`1 actualResults, DiagnosticAnalyzer analyzer, DiagnosticResult[] expectedResults) in C:\Users\ghimansh\source\repos\Analyzer3\Analyzer3\Analyzer3.Test\Verifiers\DiagnosticVerifier.cs:line 113
   at TestHelper.DiagnosticVerifier.VerifyDiagnostics(String[] sources, String language, DiagnosticAnalyzer analyzer, DiagnosticResult[] expected) in C:\Users\ghimansh\source\repos\Analyzer3\Analyzer3\Analyzer3.Test\Verifiers\DiagnosticVerifier.cs:line 91
   at TestHelper.DiagnosticVerifier.VerifyCSharpDiagnostic(String source, DiagnosticResult[] expected) in C:\Users\\source\repos\Analyzer3\Analyzer3\Analyzer3.Test\Verifiers\DiagnosticVerifier.cs:line 44
   at Analyzer3.Test.UnitTest.TestMethod1() in C:\Users\\source\repos\Analyzer3\Analyzer3\Analyzer3.Test\Analyzer3UnitTests.cs:line 21
Result Message:	
Assert.IsTrue failed. Mismatch between number of diagnostics returned, expected "0" actual "1"

Diagnostics:
// warning AD0001: Analyzer 'Analyzer3.Analyzer3Analyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.'.

* SonarC# Version -6.5        
* Visual Studio Version 2017

**Comment by duncanp-sonar** [comment] 2018-09-12 16:58
Hi @vickyrocky,
I'm going to close this issue as it seems to be a duplicate of [the issue]( https://github.com/SonarSource/sonarqube-roslyn-sdk/issues/100) you opened in the SonarQube Roslyn SDK repo, and it seems to relate more to the SDK.

**Closed by duncanp-sonar** 2018-09-12 16:58 UTC
Labels: Community

**Comment by vickyrocky** [comment] 2018-09-17 09:53
Hi @duncanp-sonar ,

Thanks for your response! I have already written analyzer for c# and i am able to use that in sonarqube so if possible can you please let me know any way to write custom rules for vb.net even any reference would be great. For information i am able to write analyzer using this DiagnosticAnalyzer(LanguageNames.VisualBasic) in c# analyzer but my unit test is failing when i am passing Test0.vb to GetCsharpDiagnosticAnalyzer so if you can share any info containing sample files about unit test that would be great. If possible please provide the info. I will be thankful for your help!
