### ISSUE TITLE
[ExcludeFromCodeCoverage] does not work in some cases.

### ISSUE THREAD

**Issue by MaxTranced** [SonarSource/sonar-csharp#1421] opened 2018-05-23 13:23 UTC
### Description

A class is marked as `[ExcludeFromCodeCoverage]` but gets included in the Code Coverage count:

```
    [ExcludeFromCodeCoverage]
    [CLSCompliant(true)]
    public static class LoggerFactory
    {
```

### Expected behavior

The `LoggerFactory` class (corresponding file) does not show up in the list of files relevant for Code Coverage.

### Actual behavior

The class / file shows up as having 106 lines and 43.5% Coverage

### Known workarounds

Using the command line works ( Key: sonar.coverage.exclusions )

### Related information

* SonarC# Version: 7.1 (build 5212)
* Visual Studio Version: 15.7.2
* If running through the Scanner for MSBuild, its version: 4.2.0.1214

**Comment by Evangelink** [comment] 2018-05-25 09:01
Hi @MaxTranced,

Could you have a quick look to see if you could manage to create a reproducer for this issue?

**Comment by MaxTranced** [comment] 2018-05-27 07:04
> Could you have a quick look to see if you could manage to create a reproducer for this issue?

I will do my best and post an example. I hope it's an easy repro...

**Comment by duncanp-sonar** [comment] 2018-06-05 17:05
@MaxTranced, I've created a separate issue for a couple of related cases: #1446

However, I can't repro the issue for the code above. A couple of questions:

* which test/coverage engine are you using (and which version)?
* are there any other classes in the same file?

Thanks.

**Comment by MaxTranced** [comment] 2018-06-06 15:15
I am using OpenCover 4.6.519
There are no other classes in the file.

I do still plan on coming up with a repro, but I first plan on updating SonarQube, just in case the fix for
https://jira.sonarsource.com/browse/SONAR-10648 is related

**Comment by Evangelink** [comment] 2018-06-26 14:17
Hi @MaxTranced,

Have you had the chance to update your SQ instance and see if the issue is still present? I'd like to be able to move forward on this problem if it's still relevant.

**Comment by MaxTranced** [comment] 2018-06-26 14:30
Not yet. Working on updating it this week.

**Comment by Evangelink** [comment] 2018-06-26 14:31
Ok! Thanks for your answer.

**Comment by MaxTranced** [comment] 2018-07-06 07:11
I can still repro on SonarQube 6.7.4.38452 and Scanner for MSBuild 4.3.1.1372

Looking at creating a repro project soon(ish).

**Comment by MaxTranced** [comment] 2018-07-06 14:49
OK, I'm including an archive with a small(ish) repro case.

Please let me know if you need clarifications for how to run the repro case.

I'm running this command on a Windows 10 box with the most recent VisualStudio Pro 2017

```
cmd.exe /C ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\VsDevCmd.bat" & pwsh -NoExit -Command "Set-Location '%cd%'""
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.7.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
PS C:\tools\repro_archive> .\BuildNewRelease.ps1
```

`LoggerFactory` is 43.5% covered in the resulting analysis. I think it should be excluded from the metrics due to the `[ExcludeFromCodeCoverage]` attribute.
[repro_archive.zip](https://github.com/SonarSource/sonar-csharp/files/2170902/repro_archive.zip)

**Comment by duncanp-sonar** [comment] 2018-07-09 16:53
Thanks for the great repro @MaxTranced. I've successfully run the repro and got the same coverage results on the _LoggerFactory_ class.

I think I can explain what is happening and how you can get the results you expect.
The SonarC# plugin is fairly simple in the way it handles code coverage reports: it knows how to read coverage files for the most common tools, and it will import that data.

It's possible to set filters in SonarQube to tell SonarQube to ignore entire files from analysis or coverage, but they work at the file level. The SonarC# plugin doesn't attempt to do any clever post-processing of the data in the coverage report based on the attributes in the code. In your repro, the generated _OpenCover.xml_ file contains results for the _LoggerFactory_ so the SonarC# plugin uploads them.

If you want to exclude code from coverage at a more granular level, you need to use the exclusion mechanism supported by the code coverage tool you are using. I'm not an expert with _OpenCover_, but I've had a look at the documentation and it looks like you need to do some additional configuration to tell _OpenCover_ which attributes to treat as indicating exclusions.

If you add the parameter `-excludebyattribute:*.ExcludeFromCodeCoverageAttribute` to the _opencover.exe_ command line in the repro build script you should find that the expected classes are excluded from the coverage report.

The SonarC# pull request that you referred to (#903) is for a slightly different issue: that's about calculating the number of lines of executable code in cases where we don't have the data from a code coverage report.

Let me know if that makes sense, and whether adding the parameter gives the results you expect.

**Comment by MaxTranced** [comment] 2018-07-10 07:46
@duncanp-sonar I've added the `-excludebyattribute:*.ExcludeFromCodeCoverageAttribute` parameter and things work as I expected.

I guess it wasn't clear to me which component is responsible for which part of this filtering. Now things are a bit more clear, thank you for the great explanation.

The current issue can be closed, as far as I'm concerned. Thank you!

**Comment by MaxTranced** [comment] 2018-07-10 07:48
Also, totally unrelated... Do you happen to know if I've reported this https://github.com/SonarSource/sonar-scanner-msbuild/issues/501 to the right place?

**Comment by duncanp-sonar** [comment] 2018-07-10 08:15
Great! I'll close this issue (and update the title slightly).

Strictly speaking, the other bug is probably in the wrong place because the code that processes the OpenCover report is in this repo. However, don't worry about it - we'll move it if necessary. It's often hard for us to know exactly which repo an issue belongs to until we've done some investigation.

**Closed by duncanp-sonar** 2018-07-10 08:15 UTC
Labels: Status: In Progress

**Comment by SGeorge007** [comment] 2021-10-14 04:08
> @duncanp-sonar I've added the `-excludebyattribute:*.ExcludeFromCodeCoverageAttribute` parameter and things work as I expected.
> 
> I guess it wasn't clear to me which component is responsible for which part of this filtering. Now things are a bit more clear, thank you for the great explanation.
> 
> The current issue can be closed, as far as I'm concerned. Thank you!

Where did you add this?

**Comment by duncanp-sonar** [comment] 2021-10-15 09:16
@SGeorge007

>  add the parameter -excludebyattribute:*.ExcludeFromCodeCoverageAttribute to the opencover.exe command line


If you have further questions, please open a thread in the [community forum](https://community.sonarsource.com/). Thanks.
