### ISSUE TITLE
Update S2325: Rule should exempt MVC / Web Api controller public methods

### ISSUE THREAD

**Issue by davejclausen** [SonarSource/sonar-csharp#733] opened 2017-08-29 22:01 UTC
By design, asp.net MVC / Web Api (public) controller action methods should not be static.  Reference: https://stackoverflow.com/questions/6126957

Could S2325 exempt such methods (not flag them for not being static)?

**Comment by valhristov** [comment] 2017-08-30 08:33
Hi @davejclausen, it will be difficult to determine if a method is a controller action, but I think we could just turn off issues from S2325 for classes that inherit from System.Web.MVC.Controller. What do you think?

**Comment by davejclausen** [comment] 2017-08-30 12:27
@valhristov, that sounds good to me. I might suggest this more specific heuristic:

Turn off issues from S2325 for *public* methods in classes that inherit from System.Web.Mvc.Controller (traditional MVC), System.Web.Http.ApiController (traditional Web Api), and Microsoft.AspNetCore.Mvc.Controller (.Net Core).

Thanks!

**Comment by Evangelink** [comment] 2017-11-21 16:33
Fixed by #971

**Closed by Evangelink** 2017-11-21 16:33 UTC
Labels: Area: Rules, Status: In Progress, Type: False Positive

**Comment by ahmettahasakar** [comment] 2018-05-30 17:27
Hello,

Does this cover classes inheriting Microsoft.AspNetCore.Mvc.Controller?

**Comment by Evangelink** [comment] 2018-05-31 08:52
Hi @ahmettahasakar,

It does https://github.com/SonarSource/sonar-csharp/pull/971/files#diff-5d09aec7fe34f25a62a9c348236846cbR58

**Comment by ahmettahasakar** [comment] 2018-05-31 09:00
Interesting. The following code is marked as an issue. Is it because of async, do you think?

```
public class MyController : Controller
{
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }
}
```

**Comment by Evangelink** [comment] 2018-05-31 09:07
Could you confirm you are using SonarAnalyzer.CSharp >= 6.7 or SonarLint for VS > 3.8? I cannot reproduce the issue locally.

**Comment by ahmettahasakar** [comment] 2018-06-04 15:19
Yes it is fixed. Thank you. Apperantly it was old version
