### ISSUE TITLE
TRX file import

### ISSUE THREAD

**Issue by george-nelson** [SonarSource/sonar-csharp#800] opened 2017-09-29 15:54 UTC
### Description

SonarQube not displaying code coverage results

### Repro steps

Please provide the steps required to reproduce the problem
Using the following VSTS tasks
1. Task : SonarQube  Scanner for MSBuild - Begin Analysis (new) Version      : 3.0.2
2. Task: SonarQube  Scanner for MSBuild - End Analysis (new) Version      : 3.0.2

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior
I was CodeCoverage percentage to be displayed on the dashboard

### Actual behavior
 CodeCoverage percentage is 0

### Known workarounds
None

### Related information
SonarQube Version | 6.5.0.27846
Log info

2017-09-29T14:15:11.3901521Z SonarQube Scanner for MSBuild 3.0.2
2017-09-29T14:15:11.3901521Z Default properties file was found at D:\A2\_work\_tasks\SonarQubeScannerMsBuildBegin_15b84ca1-b62f-4a2a-a403-89b77a063157\3.0.2\SonarQubeScannerMsBuild\SonarQube.Analysis.xml
2017-09-29T14:15:11.3901521Z Loading analysis properties from D:\A2\_work\_tasks\SonarQubeScannerMsBuildBegin_15b84ca1-b62f-4a2a-a403-89b77a063157\3.0.2\SonarQubeScannerMsBuild\SonarQube.Analysis.xml
2017-09-29T14:15:11.3901521Z Post-processing started.
2017-09-29T14:15:11.3901521Z 09:15:09.529  Fetching code coverage report information from TFS...
2017-09-29T14:15:11.3901521Z 09:15:09.529  Attempting to locate a test results (.trx) file...
2017-09-29T14:15:11.3901521Z 09:15:09.576  Looking for TRX files in: D:\A2\_work\226\TestResults, D:\A2\_work\226\s\TestResults
2017-09-29T14:15:11.3901521Z 09:15:09.576  Located a test results file: D:\A2\_work\226\s\TestResults\AutoBuildService_OMANES1477 2017-09-29 09_15_00.trx

**Comment by george-nelson** [comment] 2017-09-29 15:56
SonarQube Version | 6.5.0.27846

**Comment by Evangelink** [comment] 2017-10-13 13:26
Hi @george-nelson,
Thanks for the feedback. I am closing the ticket here because it seems to be linked to some regression within the scanner for msbuild (see this [ticket](https://jira.sonarsource.com/browse/SONARMSBRU-339)).

**Closed by Evangelink** 2017-10-13 13:26 UTC

**Comment by millusdk** [comment] 2017-12-05 14:46
Hi,
We are experiencing the same issue where TFS successfully reports the code coverage, however in SonarQube, no tests are discovered and no coverage information is available.
Do you have any timeline on when this issue will be fixed?
